# Base image
FROM nginx:latest

# Install certbot
RUN apt-get update && apt-get install -y certbot

# Copy nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80

# Entrypoint command to start Nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]
